#!/bin/sh

markus=""
ro=""
n=5

while getopts mrn: myflag ; do
    case "$myflag" in
    m)
        markus="true"
    ;;
    r)
        ro="true"
    ;;
    n)
        n="$OPTARG"
    ;;
    *)
        echo "invalid option" >&2
        exit 1;
    ;;
    esac
done

shift $((OPTIND - 1))
roster=$1

if [ "$ro" = "true" ] && [ "$markus" = "true" ]; then
    exit 1
elif [ "$ro" != "true" ] && [ "$markus" != "true" ]; then
    exit 1
fi

if [ "$markus" = "true" ]; then 
    # markus file
    # sort by utorid
    # join both files by utorid
    markus=$2
    sorted_roster=$(sort -t',' -k2,2 "$roster")
    student_grades="$(echo "$sorted_roster" | join -t',' -1 2 -2 1 -a 1 -a 2 - "$markus")"
fi;

if [ "$ro" = "true" ]; then 
    # ro file
    # sort roster by student id
    # join both files by student id
    ro=$2
    sorted_roster=$(sort -t',' -k1,1 "$roster")
    student_grades="$(echo "$sorted_roster" | join -t',' -1 1 -2 1 -a 1 -a 2 - "$ro")"
fi;

student_grades="$(echo "$student_grades" | sort -t',' -n -r -k4 -)"
students_with_grades="$(echo "$student_grades" | grep -E '^[^,]+,[^,]+,[^,]+,[0-9]+$' - | cut -d ',' -f 3-4)"

echo "$(echo "$students_with_grades" | head -n "$n" -)"