#!/bin/sh

markus=""
ro=""
n=5

while getopts m:r:n: myflag ; do
    case "$myflag" in
    m)
        markus="poo"
    ;;
    r)
        ro="poo"
    ;;
    n)
        n="$OPTARG"
    ;;
    *)
        echo "invalid option" >&2
        exit 1;
    ;;
    esac
done

shift $((OPTIND - 1))
echo n "$n"

if [ "$markus" = "poo" ]; then 
    echo $markus=$2
fi;

if [ "$ro" = "poo" ]; then 
    echo $ro=$2
fi;

roster=$1 // roster

# markus file
# sort by utorid
# join both files by utorid
sorted_roster=$(sort -t',' -k2,2 "$roster")
student_grades="$(echo "$sorted_roster" | join -t',' -1 2 -2 1 -a 1 -a 2 - "$markus")"
student_grades="$(echo "$student_grades" | sort -t',' -n -r -k4 -)"
students_with_grades="$(echo "$student_grades" | grep -E '^[^,]+,[^,]+,[^,]+,[0-9]+$' - | cut -d ',' -f 3-4)"

# ro file
# sort roster by student id
# join both files by student id
sorted_ro=$(sort -t',' -k1,1 "$ro")
student_grades="$(echo "$sorted_ro" | join -t',' -1 1 -2 1 -a 1 -a 2 - "$markus")"
student_grades="$(echo "$student_grades" | sort -t',' -n -r -k4 -)"
students_with_grades="$(echo "$student_grades" | grep -E '^[^,]+,[^,]+,[^,]+,[0-9]+$' - | cut -d ',' -f 3-4)"

echo "$(echo "$students_with_grades" | head -n "$n" -)"

# part b: use process substitution but on join